### ISSUE TITLE
совсем не рабоает

### ISSUE THREAD

**Issue by deadcxap** [luzmane/jellyfin.kinopoisk.ru#1]
Добавляю ссылку на ваш репозиторий по инструкции - в списке плагинов нового не появляется.
Скачал архив с плагином, вручную положил в папку плагинов, перезапустил сервер - плагин в списке появился, но иконки нет, при нажатии на него окно "плагин не имеет настроек".
При этом с другими репозиториями и плагинами работает корректно (проверил на плагине https://github.com/skrashevich/jellyfin-plugin-kinopoisk)

**Comment by luzmane** [comment]
а какая версия jellyfin?

**Comment by deadcxap** [comment]
Версия 10.8.10

**Comment by luzmane** [comment]
Попробуйте обновить до 10.8.11. Это минимум. Обновил описание по требованиям

**Comment by deadcxap** [comment]
Да, помогло, спасибо.
