### ISSUE TITLE
запрос функции

### ISSUE THREAD

**Issue by deadcxap** [luzmane/jellyfin.kinopoisk.ru#2]
Возможно ли получать более чем одно изображение для каждой категории? Например, как сделано в themoviedb (https://prnt.sc/ZlUAtNYS28BY)

**Comment by luzmane** [comment]
нет, это зависит не от меня, я из стороннего API получаю только одну картинку. можно обратиться к разработчику API - https://github.com/mdwitr0/kinopoiskdev

**Comment by deadcxap** [comment]
Понял, спасибо.
